"""add nester and project_manager roles, project_manager fk

Revision ID: 15f014898eea
Revises: 367537408347
Create Date: 2026-09-15 05:17:21.228120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f014898eea'
down_revision: Union[str, None] = '367537408347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adding values to an existing native Postgres enum can't run inside the
    # same transaction as other DDL, and Alembic autogenerate does not detect
    # enum-value additions at all — both called out in
    # alembic/versions/68428e0795c7_add_manager_role_room_stage_events_.py,
    # which added Manager the same way. Values are the enum members' *names*
    # (uppercase), matching what's actually stored in the user_role column
    # (SQLAlchemy's Enum type stores .name, not .value, by default) — see
    # docs/ARCHITECTURE.md §11.5.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'PROJECT_MANAGER'")
        op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'NESTER'")

    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-adjusted: `projects.project_manager` was a free-text name column;
    # it's replaced here with `project_manager_id`, a real FK to users,
    # mirroring the existing team_leader_id/team_leader pattern. Autogenerate
    # sees this as drop-column-add-column (not a rename) because it genuinely
    # is a type change (str -> FK int), not just a rename — there is no safe
    # way to carry over the old free-text values (a name typed in isn't a
    # user id), so this intentionally drops them. No production data exists
    # yet for this column (see the workflow_stages re-seed note in
    # app/models/workflow_stage.py for the same "nothing real to migrate yet"
    # reasoning) — seed.py is updated separately to populate the new column
    # via a real seeded Project Manager user.
    op.add_column('projects', sa.Column('project_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'projects_project_manager_id_fkey', 'projects', 'users',
        ['project_manager_id'], ['id'], ondelete='SET NULL',
    )
    op.drop_column('projects', 'project_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_manager', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('projects_project_manager_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'project_manager_id')
    # ### end Alembic commands ###
    # Postgres has no "DROP VALUE" for enums — removing 'PROJECT_MANAGER'/
    # 'NESTER' from user_role would require rebuilding the type. Not
    # attempted here, same as the Manager-role downgrade note in
    # 68428e0795c7; do it manually and confirm no user row uses either value
    # first if a downgrade is ever actually needed.
