"""add manager role, room stage events, comments

Revision ID: 68428e0795c7
Revises: 4327daf68c5d
Create Date: 2026-09-08 11:15:15.537301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68428e0795c7'
down_revision: Union[str, None] = '4327daf68c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adding a value to an existing native Postgres enum can't run inside the
    # same transaction as other DDL (and Alembic autogenerate doesn't detect
    # enum-value additions at all — this line was added by hand). The
    # autocommit block runs it outside the migration's transaction.
    #
    # Note the value is 'MANAGER' (uppercase), matching the existing rows in
    # this column — SQLAlchemy's Enum type stores a Python enum member's
    # *name* in the database by default (not its .value), so 'ADMIN',
    # 'TEAM_LEADER', 'DETAILER' are what's actually sitting in this column
    # today even though UserRole.TEAM_LEADER.value == "team_leader". The API
    # still returns "team_leader" etc. — Pydantic serialises .value — this
    # only affects the raw column contents.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'MANAGER'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('workflow_stage_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('NOTE', 'RFI', 'BLOCKER', name='comment_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='comment_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_comments_room_id'), 'comments', ['room_id'], unique=False)
    op.create_table('room_stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVED', 'APPROVED_WITH_COMMENTS', 'MARKUPS_REQUIRED', name='stage_transition_outcome'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['workflow_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['workflow_stages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_stage_events_room_id'), 'room_stage_events', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_stage_events_room_id'), table_name='room_stage_events')
    op.drop_table('room_stage_events')
    op.drop_index(op.f('ix_comments_room_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
    # Postgres has no "DROP VALUE" for enums — removing 'manager' from
    # user_role would require rebuilding the type. Not attempted here; if a
    # downgrade is ever actually needed, do it manually and confirm no user
    # row still uses 'manager' first.
