"""add batches

Revision ID: 79e1794040f1
Revises: 8ffac8920633
Create Date: 2026-09-15 05:26:51.184435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e1794040f1'
down_revision: Union[str, None] = '8ffac8920633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # batch_status is a brand new Postgres enum type (not an added value on
    # an existing one), created inline via sa.Enum(...) same as every other
    # enum column in the initial schema migration (priority, project_status,
    # room_workflow_status, ...) — this does NOT need the
    # autocommit_block()/ALTER TYPE ... ADD VALUE dance documented in
    # 68428e0795c7/15f014898eea/8ffac8920633; that trick is specifically for
    # adding a value to an *existing* enum type, which can't run inside the
    # same transaction as other DDL. Creating a new type has no such
    # restriction. Values are the enum members' *names* (uppercase) per
    # SQLAlchemy's default Enum-column behaviour — see docs/ARCHITECTURE.md
    # §11.5 — the API still serialises the lowercase .value.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BOM_PENDING', 'BOM_REVIEW', 'NESTING', 'COMPLETE', name='batch_status'), nullable=False),
    sa.Column('nester_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'batch_number', name='uq_batch_project_number')
    )
    op.create_index(op.f('ix_batches_project_id'), 'batches', ['project_id'], unique=False)
    op.add_column('rooms', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rooms_batch_id'), 'rooms', ['batch_id'], unique=False)
    # Named explicitly (autogenerate left this unnamed) so downgrade() can
    # target it reliably rather than relying on Postgres's default-name
    # guess, matching how 15f014898eea names projects_project_manager_id_fkey.
    op.create_foreign_key(
        'rooms_batch_id_fkey', 'rooms', 'batches', ['batch_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_batch_id_fkey', 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_batch_id'), table_name='rooms')
    op.drop_column('rooms', 'batch_id')
    op.drop_index(op.f('ix_batches_project_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
