"""add notifications

Revision ID: 972445d6ab00
Revises: 79e1794040f1
Create Date: 2026-09-15 05:31:46.215567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972445d6ab00'
down_revision: Union[str, None] = '79e1794040f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # notification_type is a brand new Postgres enum type (not an added
    # value on an existing one), created inline via sa.Enum(...) same as
    # batch_status in 79e1794040f1 — this does NOT need the
    # autocommit_block()/ALTER TYPE ... ADD VALUE dance documented in
    # 68428e0795c7/15f014898eea/8ffac8920633; that trick is specifically for
    # adding a value to an *existing* enum type, which can't run inside the
    # same transaction as other DDL. Creating a new type has no such
    # restriction. Values are the enum members' *names* (uppercase) per
    # SQLAlchemy's default Enum-column behaviour — see docs/ARCHITECTURE.md
    # §11.5 — the API still serialises the lowercase .value.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IFA_READY', 'IFC_READY', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_notifications_room_id'), 'notifications', ['room_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_room_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
