"""add weekly plan entries

Revision ID: bcc00b51ae99
Revises: e5f91237b435
Create Date: 2026-09-09 10:15:54.788779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc00b51ae99'
down_revision: Union[str, None] = 'e5f91237b435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'week_start', name='uq_weekly_plan_entry')
    )
    op.create_index(op.f('ix_weekly_plan_entries_project_id'), 'weekly_plan_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_weekly_plan_entries_user_id'), 'weekly_plan_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_plan_entries_week_start'), 'weekly_plan_entries', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_plan_entries_week_start'), table_name='weekly_plan_entries')
    op.drop_index(op.f('ix_weekly_plan_entries_user_id'), table_name='weekly_plan_entries')
    op.drop_index(op.f('ix_weekly_plan_entries_project_id'), table_name='weekly_plan_entries')
    op.drop_table('weekly_plan_entries')
    # ### end Alembic commands ###
